services:
  api-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2989:2989"
    volumes:
      - ./content:/app/content
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    driver: bridge